# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Harshit Patni
tagline:          'Undergrad at IIIT-Hyderabad'
description:      "GSoC 17 student developer working on 2d Color Maps with Matplotlib, NumFOCUS"
#url:              http://jonathonbechtel.com
baseurl:          /
comments:         true

author:
  gravatar_md5:  783fc5ac9e9762db9407533a116bef93
  name:           'Harshit Patni'
  url:            http://jonathonbechtel.com 
  linkedin:       patniharshit
  github:         patniharshit
  email:          patniharshit@gmail.com


paginate:         5
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap]
paginate_path: "page:num"

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/jbechtel/jbechtel.github.io

